name: Deploy
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: Debug Info
        uses: hmarr/debug-action@v2
      - uses: actions/checkout@v3
      - name: Run deploy
        run: echo ${{ vars.ENVI }}

